import streamlit as st
import numpy as np
import joblib

# ── Page config ──────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="DiabetaCheck | Diabetes Risk Classifier",
    page_icon="🩺",
    layout="centered",
)

# ── Load model & scaler ───────────────────────────────────────────────────────
@st.cache_resource
def load_model():
    model  = joblib.load("model.pkl")
    scaler = joblib.load("scaler.pkl")
    return model, scaler

model, scaler = load_model()

# ── Custom CSS ────────────────────────────────────────────────────────────────
st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

    html, body, [class*="css"] { font-family: 'Inter', sans-serif; }

    .main { background-color: #f8fafc; }

    .header-box {
        background: linear-gradient(135deg, #1e3a5f 0%, #2d6a9f 100%);
        border-radius: 16px;
        padding: 2rem 2.5rem;
        margin-bottom: 1.5rem;
        color: white;
    }
    .header-box h1 { font-size: 2rem; font-weight: 700; margin: 0 0 .3rem 0; }
    .header-box p  { font-size: 1rem; opacity: .85; margin: 0; }

    .disclaimer-box {
        background: #fff8e1;
        border-left: 4px solid #f59e0b;
        border-radius: 8px;
        padding: 1rem 1.25rem;
        margin-bottom: 1.5rem;
        font-size: .875rem;
        color: #78350f;
    }
    .disclaimer-box strong { color: #92400e; }

    .result-card {
        border-radius: 12px;
        padding: 1.5rem 2rem;
        text-align: center;
        margin-top: 1rem;
        font-size: 1.5rem;
        font-weight: 700;
    }
    .result-N { background:#dcfce7; border:2px solid #16a34a; color:#15803d; }
    .result-P { background:#fef9c3; border:2px solid #ca8a04; color:#92400e; }
    .result-Y { background:#fee2e2; border:2px solid #dc2626; color:#b91c1c; }

    .metric-row { display:flex; gap:1rem; margin-bottom:1rem; }
    .metric-box {
        flex:1; background:white; border-radius:10px;
        padding:1rem; text-align:center;
        box-shadow: 0 1px 3px rgba(0,0,0,.08);
    }
    .metric-box .val { font-size:1.6rem; font-weight:700; color:#1e3a5f; }
    .metric-box .lbl { font-size:.75rem; color:#64748b; margin-top:.2rem; }

    .stSlider > div > div > div > div { background:#2d6a9f !important; }
    .stButton > button {
        background: linear-gradient(135deg, #1e3a5f, #2d6a9f);
        color: white; border:none; border-radius:8px;
        padding:.65rem 2rem; font-weight:600; width:100%;
        font-size:1rem; cursor:pointer;
    }
    .stButton > button:hover { opacity:.9; }
    footer { visibility: hidden; }
</style>
""", unsafe_allow_html=True)

# ── Header ────────────────────────────────────────────────────────────────────
st.markdown("""
<div class="header-box">
    <h1>🩺 DiabetaCheck</h1>
    <p>Multiclass Diabetes Risk Classifier &nbsp;·&nbsp; SVM Model &nbsp;·&nbsp; IIT Delhi Capstone Project</p>
</div>
""", unsafe_allow_html=True)

# ── Disclaimer ────────────────────────────────────────────────────────────────
st.markdown("""
<div class="disclaimer-box">
    <strong>⚠️ Medical Disclaimer — Please Read Before Use</strong><br>
    This is a <strong>Minimum Viable Product (MVP)</strong> built for academic demonstration only.
    It is <strong>not a diagnostic tool</strong> and must <strong>not</strong> be used as a substitute
    for professional medical advice, diagnosis, or treatment. Results are generated by a machine
    learning model trained on a limited dataset and may be inaccurate. Always consult a qualified
    healthcare professional for any health concerns. <strong>Clinically correlate all outputs.</strong>
</div>
""", unsafe_allow_html=True)

# ── Model info strip ──────────────────────────────────────────────────────────
c1, c2, c3 = st.columns(3)
c1.metric("Algorithm", "SVM (RBF Kernel)")
c2.metric("Model Accuracy", "95.5%")
c3.metric("Dataset Size", "1,000 patients")

st.divider()

# ── Input form ────────────────────────────────────────────────────────────────
st.subheader("Enter Patient Biomarkers")
st.caption("Top 5 clinically significant features selected by feature importance analysis.")

col1, col2 = st.columns(2)

with col1:
    hba1c = st.number_input(
        "HbA1c (%)",
        min_value=0.5, max_value=20.0, value=5.5, step=0.1,
        help="Glycated haemoglobin — primary indicator of long-term blood glucose control."
    )
    bmi = st.number_input(
        "BMI (kg/m²)",
        min_value=10.0, max_value=60.0, value=23.0, step=0.1,
        help="Body Mass Index — weight in kg divided by height in m²."
    )
    age = st.number_input(
        "Age (years)",
        min_value=1, max_value=100, value=35, step=1,
        help="Patient's age in years."
    )

with col2:
    chol = st.number_input(
        "Total Cholesterol (mmol/L)",
        min_value=0.5, max_value=15.0, value=4.5, step=0.1,
        help="Total serum cholesterol level."
    )
    tg = st.number_input(
        "Triglycerides (mmol/L)",
        min_value=0.1, max_value=20.0, value=1.2, step=0.1,
        help="Serum triglyceride level."
    )

st.write("")

# ── Predict ───────────────────────────────────────────────────────────────────
if st.button("Predict Diabetes Risk"):
    input_arr = np.array([[hba1c, bmi, age, chol, tg]])
    input_scaled = scaler.transform(input_arr)
    prediction = model.predict(input_scaled)[0]
    proba = model.predict_proba(input_scaled)[0]
    classes = model.classes_  # ['N', 'P', 'Y']

    label_map = {
        'N': ("🟢 Non-Diabetic", "result-N", "Low risk. Maintain a healthy lifestyle with regular check-ups."),
        'P': ("🟡 Pre-Diabetic",  "result-P", "Borderline risk detected. Lifestyle modifications strongly advised. Consult a physician."),
        'Y': ("🔴 Diabetic",      "result-Y", "High risk indicated. Please seek immediate medical consultation. Clinically correlate.")
    }

    title, css_class, advice = label_map[prediction]

    st.markdown(f'<div class="result-card {css_class}">{title}</div>', unsafe_allow_html=True)
    st.info(f"**Clinical Note:** {advice}")

    # Probability breakdown
    st.subheader("Confidence Breakdown")
    for cls, prob in zip(classes, proba):
        names = {'N': 'Non-Diabetic', 'P': 'Pre-Diabetic', 'Y': 'Diabetic'}
        colors = {'N': '#16a34a', 'P': '#ca8a04', 'Y': '#dc2626'}
        st.markdown(f"**{names[cls]}**")
        st.progress(float(prob))
        st.caption(f"{prob*100:.1f}% confidence")

    st.warning(
        "🔬 **Remember:** This prediction is generated by an ML model trained on a limited academic dataset. "
        "It is an MVP and must be clinically correlated. Not a substitute for laboratory tests or physician judgement."
    )

# ── Footer ────────────────────────────────────────────────────────────────────
st.divider()
st.markdown("""
<div style="text-align:center; color:#94a3b8; font-size:.8rem; padding-bottom:1rem;">
    <strong>Capstone Project 1</strong> · AI in Healthcare · IIT Delhi Executive Program<br>
    Model: SVM (RBF, C=10) · Features: HbA1c, BMI, Age, Cholesterol, Triglycerides<br>
    <em>For academic and demonstration purposes only. Not for clinical use.</em>
</div>
""", unsafe_allow_html=True)
